# Generated by Django 3.2.15 on 2022-10-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit',
            field=models.CharField(default=0, max_length=50, verbose_name='単位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.CharField(default=0, max_length=50, verbose_name='単価'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CustomerID', to='sales.customer'),
        ),
    ]
