# Generated by Django 3.2.15 on 2022-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_product_id_order_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=0, max_length=50, verbose_name='顧客名'),
            preserve_default=False,
        ),
    ]
