# Generated by Django 3.2.15 on 2022-10-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_order_desired_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='desired_delivery_date',
            new_name='delivery_date',
        ),
    ]
