# Generated by Django 3.2.15 on 2022-12-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_desired_delivery_date_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=1, max_length=50, verbose_name='ユーザID'),
            preserve_default=False,
        ),
    ]
