# Generated by Django 3.2.15 on 2022-12-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.CharField(default=1, max_length=50, verbose_name='ユーザID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.CharField(default=1, max_length=50, verbose_name='ユーザID'),
            preserve_default=False,
        ),
    ]
