# Generated by Django 3.2.15 on 2022-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20221205_1317'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('customer_name', 'user'), name='unique_customer'),
        ),
    ]
