# Generated by Django 3.2.15 on 2022-12-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_customer_unique_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='顧客様名'),
        ),
    ]
